#
# ### Continuous Integration
#
# Ensure that code successfully builds and passes tests.
#
# Right now, I am also building packages every time. In the future, package building
# can be saved for release pipeline.
#

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
- template: vars/vars-ci.yaml
- template: vars/vars-all.yaml

steps:
- template: steps/signing-cert.yaml
- template: steps/git-checkout.yaml
- template: steps/build-test.yaml
- template: steps/make-slide.yaml
- template: steps/publish-msix.yaml
  parameters:
    platform: arm64
- template: steps/publish-msix.yaml
  parameters:
    platform: x64
- template: steps/publish-artifact.yaml
