#
# ### Continuous Integration
#
# Ensure that code successfully builds and passes tests
#

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
- template: vars/vars-ci.yaml
- template: vars/vars-all.yaml

steps:
- template: steps/signing-cert.yaml
- template: steps/git-checkout.yaml
#- template: steps/build-test.yaml
- template: steps/publish-msix.yaml
