[config]
text_distace = 0.27
text_width = 0.67
text_height = 0.24
icon_size = 0.21
dpi = 96.0

[logos.blender]
title = "Hello, Blender"
path = "blender_icon_128x128.png"

[logos.wine]
title = "Wine O'Clock"
path = "wine-svgrepo-com.svg"

[[rows]]
xposition = 1.2
yposition = 1.12
width = 4.85
logos = [ "wine", "blender", "blender", "blender", "blender", "blender", "blender" ]

[[rows]]
xposition = 1.2
yposition = 1.72
width = 4.85
logos = ["blender", "blender", "blender", "blender", "blender", "blender", "blender", "blender", "blender"]
