[config]
text_distace = 0.27
text_width = 0.67
text_height = 0.24
icon_size = 0.21
dpi = 96.0

[logos.blender]
title = "Hello, Blender"
path = "blender_icon_128x128.png"

[logos.wine]
title = "Wine O'Clock"
path = "wine-svgrepo-com.svg"

[logos.one]
title = "1x1 Square"
path = "1x1.svg"

[logos.two]
title = "3x2 Mid-Wide"
path = "3x2.svg"

[logos.three]
title = "3x1 Super Wide"
path = "3x1.svg"

[logos.five]
title = "5x1 Very Wide"
path = "5x1.svg"

[logos.seven]
title = "7x1 Epic Wide"
path = "7x1.svg"

[logos.nine]
title = "9x1 Insane Wide"
path = "9x1.svg"

#
#
#

[[rows]]
xposition = 1.31
yposition = 1.21
width = 4.85
logos = [ "three", "wine", "one", "two", "one", "one", "five" ]

[[rows]]
xposition = 1.31
yposition = 1.84
width = 4.85
logos = ["one", "seven", "nine", "one", "five", "nine", "nine" ]

#
#
#

[[rows]]
xposition = 1.31
yposition = 2.71
width = 4.85
logos = [ "three", "one" ]

[[rows]]
xposition = 1.31
yposition = 3.34
width = 4.85
logos = [ "one" ]

[[rows]]
xposition = 1.31
yposition = 3.97
width = 4.85
logos = [ "one" ]

#
#
#

[[rows]]
xposition = 1.31
yposition = 4.88
width = 4.85
logos = [ "one" ]

[[rows]]
xposition = 1.31
yposition = 5.50
width = 4.85
logos = [ "two", "one" ]

#
#
#

[[rows]]
xposition = 1.31
yposition = 6.58
width = 4.85
logos = [ "two", "one" ]

#
# ----------------------------------
#


[[rows]]
xposition = 7.66
yposition = 1.21
width = 4.85
logos = [ "five", "one" ]

[[rows]]
xposition = 7.66
yposition = 1.84
width = 4.85
logos = [ "five", "one" ]

#
#
#

[[rows]]
xposition = 7.66
yposition = 2.71
width = 4.85
logos = [ "five", "one" ]

[[rows]]
xposition = 7.66
yposition = 3.34
width = 4.85
logos = [ "five", "one" ]

[[rows]]
xposition = 7.66
yposition = 3.97
width = 4.85
logos = [ "five", "one" ]

#
#
#

[[rows]]
xposition = 7.66
yposition = 4.88
width = 4.85
logos = [ "five", "one" ]

[[rows]]
xposition = 7.66
yposition = 5.50
width = 4.85
logos = [ "five", "one" ]

#
#
#

[[rows]]
xposition = 7.66
yposition = 6.58
width = 4.85
logos = [ "five", "one" ]
