[files]
template.bitmaps = [ "Slide1.PNG" ]
template.slides = "template.pptx"

[layout]
line_spacing = 1.45
padding = 0.25

[render]
icon_size = 0.7
text_height = 0.5
text_distace = 0.75 
text_width = 0.8
font_size = 12
dpi = 96

[logos.wine]
title = "Glass of Wine"
path = "wine-local.png"

[logos.wine-svg]
title = "Glass of Wine (SVG)"
path = "wine-svgrepo-com.svg"

[[boxes]]
logos.1 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
logos.2 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
outer = { x = 0.87, y = 2.51, width = 5.71, height = 4 }
min_columns = 4
auto_flow = true

[[boxes]]
logos.1 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
logos.2 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
outer = { x = 6.78, y = 2.51, width = 5.71, height = 4 }
min_columns = 4
auto_flow = true
