[files]
output = "out/sample-packed.pptx"
template.bitmaps = [ "Slide1.PNG" ]

[layout]
line_spacing = 1.45
padding = 0.25

[render]
icon_size = 0.7
text_height = 0.5
text_distace = 0.75 
text_width = 0.8
font_size = 12
dpi = 96

[logos.wine]
title = "Glass of Wine"
path = "wine-local.png"

[logos.wine-svg]
title = "Glass of Wine (SVG)"
path = "wine-svgrepo-com.svg"

[[boxes]]
logos.1 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
logos.2 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
outer = { x = 0.3333, y = 0.3333, width = 6.15, height = 3.26 }
min_columns = 4
auto_flow = true

[[boxes]]
logos.1 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
logos.2 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
outer = { x = 0.3333, y = 3.91, width = 6.15, height = 3.26 }
min_columns = 4
auto_flow = true

[[boxes]]
logos.1 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
logos.2 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
outer = { x = 6.85, y = 0.3333, width = 6.15, height = 3.26 }
min_columns = 4
auto_flow = true

[[boxes]]
logos.1 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
logos.2 = [ "wine", "wine", "wine", "wine", "wine", "wine" ]
outer = { x = 6.85, y = 3.91, width = 6.15, height = 3.26 }
min_columns = 4
auto_flow = true
