[files]
template.slides = "template.pptx"
template.bitmaps = "template.png"

[layout]
title = "Logo Slide Maker Sample"
line_spacing = 1.28
padding = 0.25

[render]
text_distace = 0.6
text_width = 1.27
text_height = 0.5
icon_size = 0.55
dpi = 96.0
font_size = 10.5
font_name = "Segoe UI"
font_color = "595959"

[[variants]]
name = "Sample Slide"
description = [ "Cloud Native Projects", "Windows OSS Apps" ]

[[boxes]]
title = "Cloud Native Projects"
outer = { x = 0.87, y = 2.51, width = 5.71, height = 4 }
logos.1 = [ "crio", "coredns", "envoy", "etcd", "flux" ]
logos.2 = [ "helm", "istio", "k8s", "linkerd" ]
logos.3 = [ "prometheus", "spire", "vitess" ]
min_columns = 4
auto_flow = true

[logos.k8s]
title = "Scheduling & Orchestration"
path = "cloud/k8s.svg"
scale = 1.4

[logos.prometheus]
title = "Observability"
path = "cloud/prometheus.svg"

[logos.spire]
title = "Key Management"
path = "cloud/spire.svg"

[logos.helm]
title = "Application Definition & Image Build"
path = "cloud/helm.svg"

[logos.flux]
title = "Continuous Integration & Delivery"
path = "cloud/flux.svg"

[logos.etcd]
title = "Coordination & Service Discovery"
path = "cloud/etcd.svg"
scale = 0.85

[logos.istio]
title = "Service Mesh"
path = "cloud/istio.svg"

[logos.coredns]
title = "Coordination & Service Discovery"
path = "cloud/coredns.svg"

[logos.crio]
title = "Container Runtime"
path = "cloud/crio.svg"
scale = 0.9

[logos.envoy]
title = "Service Proxy"
path = "cloud/envoy.svg"

[logos.vitess]
title = "Database"
path = "cloud/vitess.svg"

[logos.linkerd]
title = "Service Mesh"
path = "cloud/linkerd.svg"

[logos.one]
title = "1x1 Square"
path = "1x1.svg"
text_width = 0.5

[[boxes]]
title = "Windows OSS Apps"
outer = { x = 6.78, y = 2.51, width = 5.71, height = 4 }
logos.1 = [ "audacity", "blender", "freecad", "gimp", "inkscape" ]
logos.2 = [ "kodi", "libreoffice", "scribus", "shotcut", "sweethome" ]
logos.3 = [ "tor", "vlc" ]
min_columns = 4
auto_flow = true

[logos.gimp]
title = "Gimp"
path = "desktop/gimp.svg"

[logos.blender]
title = "Blender"
path = "desktop/blender.svg"

[logos.audacity]
title = "Audacity"
path = "desktop/audacity.svg"

[logos.inkscape]
title = "Inkscape"
path = "desktop/inkscape.svg"

[logos.shotcut]
title = "Shotcut"
path = "desktop/shotcut.svg"

[logos.libreoffice]
title = "LibreOffice"
path = "desktop/libre-office.svg"

[logos.kodi]
title = "Kodi"
path = "desktop/kodi.svg"

[logos.vlc]
title = "VLC Media Player"
path = "desktop/vlc.svg"

[logos.freecad]
title = "FreeCAD"
path = "desktop/freecad.svg"

[logos.sweethome]
title = "Sweet Home 3D"
path = "desktop/sweethome.png"

[logos.scribus]
title = "Scribus"
path = "desktop/scribus.svg"

[logos.tor]
title = "Tor Browser"
path = "desktop/tor-browser.svg"

