steps:
- task: DownloadSecureFile@1
  name: configToml
  inputs:
    secureFile: 'config.toml'
  displayName: 'Download configuration file'
- powershell : Move-Item $(signingCert.secureFilePath) $(Solution.PackageDirectory)
  displayName: 'Move configuration file into WunUi directory'