steps:
- task: DownloadSecureFile@1
  name: configToml
  inputs:
    secureFile: 'config.toml'
  displayName: 'Download configuration file'
- powershell : Move-Item $(configToml.secureFilePath) $(Solution.PackageDirectory)
  displayName: 'Move configuration file into WunUi directory'
- powershell : ls $(Solution.PackageDirectory)
  displayName: 'Dump directory of WinUI, to confirm config.toml arrived'
